export const regions = [
  "Hlavní město Praha",
  "Středočeský kraj",
  "Jihočeský kraj",
  "Plzeňský kraj",
  "Karlovarský kraj",
  "Ústecký kraj",
  "Liberecký kraj",
  "Královéhradecký kraj",
  "Pardubický kraj",
  "Kraj Vysočina",
  "Jihomoravský kraj",
  "Olomoucký kraj",
  "Moravskoslezský kraj",
  "Zlínský kraj",
];

export const citiesByRegion: Record<string, string[]> = {
  "Hlavní město Praha": [
    "Praha",
  ],

  "Středočeský kraj": [
    "Benešov",
    "Beroun",
    "Brandýs nad Labem-Stará Boleslav",
    "Čáslav",
    "Čelákovice",
    "Český Brod",
    "Dobříš",
    "Hořovice",
    "Hostivice",
    "Kladno",
    "Kolín",
    "Kralupy nad Vltavou",
    "Kutná Hora",
    "Lysá nad Labem",
    "Mělník",
    "Mladá Boleslav",
    "Mnichovo Hradiště",
    "Neratovice",
    "Nymburk",
    "Poděbrady",
    "Příbram",
    "Rakovník",
    "Říčany",
    "Slaný",
    "Vlašim",
    "Votice",
    "Zruč nad Sázavou",
  ],

  "Jihočeský kraj": [
    "Bechyně",
    "Blatná",
    "České Budějovice",
    "Český Krumlov",
    "Dačice",
    "Hluboká nad Vltavou",
    "Jindřichův Hradec",
    "Kaplice",
    "Milevsko",
    "Netolice",
    "Nová Bystřice",
    "Písek",
    "Prachatice",
    "Protivín",
    "Sezimovo Ústí",
    "Soběslav",
    "Strakonice",
    "Suchdol nad Lužnicí",
    "Tábor",
    "Třeboň",
    "Týn nad Vltavou",
    "Velešín",
    "Vimperk",
    "Vodňany",
  ],

  "Plzeňský kraj": [
    "Blovice",
    "Domažlice",
    "Dobřany",
    "Horažďovice",
    "Horšovský Týn",
    "Klatovy",
    "Nýrsko",
    "Plzeň",
    "Planá",
    "Rokycany",
    "Stod",
    "Stříbro",
    "Sušice",
    "Tachov",
  ],

  "Karlovarský kraj": [
    "Aš",
    "Cheb",
    "Chodov",
    "Františkovy Lázně",
    "Horní Slavkov",
    "Karlovy Vary",
    "Kraslice",
    "Loket",
    "Mariánské Lázně",
    "Nejdek",
    "Ostrov",
    "Sokolov",
  ],

  "Ústecký kraj": [
    "Bílina",
    "Děčín",
    "Dubí",
    "Chomutov",
    "Jirkov",
    "Klášterec nad Ohří",
    "Kadaň",
    "Litoměřice",
    "Litvínov",
    "Louny",
    "Lovosice",
    "Most",
    "Roudnice nad Labem",
    "Rumburk",
    "Teplice",
    "Terezín",
    "Ústí nad Labem",
    "Varnsdorf",
    "Žatec",
  ],

  "Liberecký kraj": [
    "Česká Lípa",
    "Frýdlant",
    "Jablonec nad Nisou",
    "Jilemnice",
    "Liberec",
    "Nový Bor",
    "Semily",
    "Tanvald",
    "Turnov",
    "Železný Brod",
  ],

  "Královéhradecký kraj": [
    "Broumov",
    "Dvůr Králové nad Labem",
    "Hořice",
    "Hradec Králové",
    "Jaroměř",
    "Jičín",
    "Kostelec nad Orlicí",
    "Náchod",
    "Nová Paka",
    "Nové Město nad Metují",
    "Rychnov nad Kněžnou",
    "Trutnov",
    "Vrchlabí",
  ],

  "Pardubický kraj": [
    "Česká Třebová",
    "Hlinsko",
    "Holice",
    "Chrudim",
    "Jevíčko",
    "Králíky",
    "Lanškroun",
    "Litomyšl",
    "Moravská Třebová",
    "Pardubice",
    "Polička",
    "Přelouč",
    "Svitavy",
    "Ústí nad Orlicí",
    "Vysoké Mýto",
  ],

  "Kraj Vysočina": [
    "Bystřice nad Pernštejnem",
    "Chotěboř",
    "Havlíčkův Brod",
    "Humpolec",
    "Jemnice",
    "Jihlava",
    "Ledeč nad Sázavou",
    "Moravské Budějovice",
    "Nové Město na Moravě",
    "Pacov",
    "Pelhřimov",
    "Světlá nad Sázavou",
    "Telč",
    "Třebíč",
    "Velké Meziříčí",
    "Žďár nad Sázavou",
  ],

  "Jihomoravský kraj": [
    "Blansko",
    "Boskovice",
    "Brno",
    "Břeclav",
    "Bučovice",
    "Dubňany",
    "Hodonín",
    "Ivančice",
    "Kyjov",
    "Kuřim",
    "Letovice",
    "Mikulov",
    "Moravský Krumlov",
    "Pohořelice",
    "Rosice",
    "Slavkov u Brna",
    "Tišnov",
    "Veselí nad Moravou",
    "Vyškov",
    "Znojmo",
  ],

  "Olomoucký kraj": [
    "Hanušovice",
    "Jeseník",
    "Konice",
    "Litovel",
    "Lipník nad Bečvou",
    "Mohelnice",
    "Olomouc",
    "Prostějov",
    "Přerov",
    "Šternberk",
    "Šumperk",
    "Uničov",
    "Zábřeh",
  ],

  "Moravskoslezský kraj": [
    "Bílovec",
    "Bohumín",
    "Bruntál",
    "Český Těšín",
    "Frýdek-Místek",
    "Frenštát pod Radhoštěm",
    "Havířov",
    "Hlučín",
    "Jablunkov",
    "Karviná",
    "Kopřivnice",
    "Kravaře",
    "Krnov",
    "Nový Jičín",
    "Odry",
    "Opava",
    "Orlová",
    "Ostrava",
    "Rýmařov",
    "Třinec",
    "Vítkov",
  ],

  "Zlínský kraj": [
    "Bojkovice",
    "Bystřice pod Hostýnem",
    "Holešov",
    "Kroměříž",
    "Luhačovice",
    "Napajedla",
    "Otrokovice",
    "Rožnov pod Radhoštěm",
    "Slavičín",
    "Uherské Hradiště",
    "Uherský Brod",
    "Valašské Klobouky",
    "Valašské Meziříčí",
    "Vizovice",
    "Vsetín",
    "Zlín",
  ],
};

export function getCitiesForRegion(region: string) {
  return citiesByRegion[region] || [];
}
